[package]
name = "audio-courier"
version = "1.0.1"
description = "A Tauri App for audio capture"
authors = ["superwindcloud"]
edition = "2021"
homepage = "https://github.com/super1windcloud/audio-courier"
repository = "https://github.com/super1windcloud/audio-courier"
license = "GPL"

[lib]
name = "tauri_courier_ai_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
tauri = { version = "2", features = ["macos-private-api"] }
tauri-plugin-opener = "2"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
cpal = "0.16.0"
tokio-stream = "0.1.17"
reqwest = { version = "0.12.23", features = ["json", "stream"] }
dotenv = "0.15.0"
tokio = "1.47.1"
vosk = "0.3.1"
rand = "0.9.2"


hound = "3.5.1"
dirs = "6.0.0"
dasp = "0.11.0"

[target.'cfg(not(any(target_os = "android", target_os = "ios")))'.dependencies]
tauri-plugin-global-shortcut = "2"

