[package]
name = "audio-courier"
version = "1.0.1"
description = "A Tauri App for audio capture"
authors = ["superwindcloud"]
edition = "2021"
homepage = "https://github.com/super1windcloud/audio-courier"
repository = "https://github.com/super1windcloud/audio-courier"
license = "GPL"
default-run = "audio-courier"

[lib]
name = "tauri_courier_ai_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
tauri = { version = "2", features = ["macos-private-api"] }
tauri-plugin-opener = "2"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
cpal = "0.16.0"
tokio-stream = "0.1.17"
reqwest = { version = "0.12.23", features = ["json", "multipart", "stream", "gzip", "brotli"] }
dotenv = "0.15.0"
tokio = { version = "1.47.1", features = ["rt-multi-thread", "macros"] }
vosk = "0.3.1"
rand = "0.9.2"

hound = "3.5.1"
dirs = "6.0.0"
dasp = "0.11.0"
rubato = "0.16.2"
anyhow = "1.0.100"
samplerate-rs = "0.1.0"
base64 = "0.22.1"
chrono = "0.4.42"
futures-util = "0.3.31"
hmac = "0.13.0-rc.2"
sha1 = "0.11.0-rc.2"
tokio-tungstenite = { version = "0.28.0", features = ["rustls-tls-webpki-roots"] }
tungstenite = { version = "0.28.0", features = ["rustls-tls-webpki-roots"] }
uuid = { version = "1.18.1", features = ["v4"] }
urlencoding = "2.1.3"
serde_urlencoded = "0.7.1"
rustls = { version = "0.23.33", features = ["ring"] }

[target.'cfg(not(any(target_os = "android", target_os = "ios")))'.dependencies]
tauri-plugin-global-shortcut = "2"


[[bin]]
name = "transfer"
path = "src/bin/transfer.rs"


[[bin]]
name = "rstar"
path = "src/bin/rstar.rs"
